apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: scaling
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50