---
apiVersion: v1
kind: Service
metadata:
  name: countries-service
spec:
  ports:
  - port: 80
    targetPort: api-port
    protocol: TCP
  selector:
    app: countries-application
    version: v1
  type: LoadBalancer