---
apiVersion: v1
kind: Service
metadata:
  name: countries-service
  labels:
    app: countries-application
spec:
  type: NodePort
  ports:
  - port: 4567
    nodePort: 31403
    targetPort: 4567
    protocol: TCP
    name: http
  selector:
    app: countries-application
    version: v1