apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: state-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: state-application
        version: v1
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
      - name: state
        env:
          - name: CLUSTER_VOLUME_PATH
            value: /data/tracker
        image: ACCOUNTID.dkr.ecr.REGION.amazonaws.com/micro_state_tracker
        ports:
          - name: state-port
            containerPort: 4567
        volumeMounts:
          - name: data-tracker
            mountPath: /data/tracker
      volumes:
      - name: data-tracker
        hostPath:
          # some path in node
          path: /home/ubuntu/efs/data/tracker