---
apiVersion: v1
kind: Service
metadata:
  name: state-service
  labels:
    app: state-application
spec:
  type: NodePort
  ports:
  - port: 4567
    nodePort: 31405
    targetPort: 4567
    protocol: TCP
    name: http
  selector:
    app: state-application
    version: v1