---
apiVersion: v1
kind: Service
metadata:
  name: state-service
spec:
  ports:
  - port: 80
    targetPort: state-port
    protocol: TCP
  selector:
    app: state-application
    version: v1
  type: LoadBalancer