apiVersion: v1
kind: PersistentVolume
metadata:
  name: state-efs-volume
spec:
  capacity:
    storage: 100Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /data
    server: {{efs-dns}}
    readOnly: false