---
apiVersion: v1
kind: Service
metadata:
  name: stress-service
spec:
  ports:
  - port: 80
    targetPort: stress-port
    protocol: TCP
  selector:
    app: stress-application
    version: v1
  type: LoadBalancer